# -*- coding: utf-8 -*-
"""K43- Đàm Thanh Bình - Project 2 Python

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g2gccx3qAT5N3hDwoZGzcHEQfl_tbvHk

**Part I: EDA - Explore Data Analysis**
"""

#Import pandas
import pandas as pd

#Import data
dftransactions=pd.read_csv('/transactions.csv')
dfpayment=pd.read_csv('/payment_report.csv')
dfproduct=pd.read_csv('/product.csv')

#Merge payment_report.csv with product.csv
dfpayment_enriched=pd.merge(dfpayment,dfproduct,how='left',left_on='product_id',right_on='product_id')

#Step1: Explore Data

"""1. Table:  **dfpayment_enriched**

Step 1: Explore Data
"""

#1/ xem dữ liệu mẫu .head()
dfpayment_enriched.head(6)

#2/ kiểm tra kiểu dữ liệu, missing .info()
dfpayment_enriched.info()

"""


*   Missing: **category, team_own** (22 missing rows)

⇒ Kiểm tra các hàng missing này thuộc product_ID nào, có ở table dfproduct không. Nếu có thì do lỗi gì mà không merge được sang table dfpayment


---


*   Data type: **report_month** stored as object, verify if should be datetime

⇒ Đổi kiểu dữ liệu report_month column về datetime


"""

#3/thống kê dữ liệu số .describe()
dfpayment_enriched.describe()

"""**Hướng dẫn đọc describe()**
1.   Missing data: if count < total rows → there are missing values.
2. Incorrect / Invalid values: check min and max for impossible values (e.g. <0, >100%, unexpected =0), based on business logic.
3. Potential outliers: if max >> 75% (Q3) → possible outliers (then verify with IQR).
4. Skewed distribution: compare mean vs 50% (median)
*   mean > median → right-skewed
*   mean < median → left-skewed
5. Variability: check std
- high std → large variation
- low std → more stable distribution
6. Spread (Central distribution): check Q1 (25%) and Q3 (75%)
- wide gap → data spread out
- narrow gap → data concentrated

**Note:** ID columns exception: ignore mean/std/median for ID fields (e.g. product_id, user_id) since they are identifiers, not numeric measures. Use them for uniqueness, duplicates, and joins instead.

Với bảng này: Chỉ đọc kết quả cột volumn:

- No missing in volume (count = 919)
- No obvious incorrect values (min > 0)
- Potential outliers: max much larger than Q3
- Distribution appears right-skewed (mean > median)

- High variability based on std
"""

#4/phân bố categorical .value_counts()
dfpayment_enriched['report_month'].value_counts()

dfpayment_enriched['payment_group'].value_counts()

dfpayment_enriched['product_id'].value_counts()

dfpayment_enriched['source_id'].value_counts()

dfpayment_enriched['category'].value_counts()

dfpayment_enriched['team_own'].value_counts()

#5/Histogram: xem phân phối dữ liệu #sns.histplot(data=DATAFRAME, x="COLUMN")
import seaborn as sns
import matplotlib.pyplot as plt
fig, ax=plt.subplots(figsize=(6,3))
sns.histplot(data=dfpayment_enriched, x="volume",bins=20)
plt.show()

sns.boxplot(x=dfpayment_enriched["volume"])
plt.show()

import seaborn as sns

sns.histplot(
    np.log1p(dfpayment_enriched["volume"]),
    bins=30
)
plt.show()

"""Step 2: Data validation"""

#1/ chỉ xem kiểu dữ liệu .dtypes
dfpayment_enriched.dtypes

#Chỉnh kiểu dữ liệu
dfpayment_enriched['report_month']=pd.to_datetime(dfpayment_enriched['report_month'])

dfpayment_enriched.dtypes

#2/Kiểm tra dữ liệu phân loại
dfpayment_enriched['payment_group'].isin(['payment','refund'])

#Đếm số dòng bị lỗi giá trị
mask = dfpayment_enriched['payment_group'].isin(['payment','refund'])
print((~mask).sum())

#Hiển thị các dòng bị lỗi (Bảng này đang đúng hết nên ko hiện dòng nào)
dfpayment_enriched[~mask]

#Check duplicated
dfpayment_enriched.duplicated().sum()

#3. Group by => (Chưa hiểu phần này)
sns.boxplot(y="volume",x="source_id",data=dfpayment_enriched)
plt.show()

sns.boxplot(x="volume",y="category",data=dfpayment_enriched)
plt.show()

"""Step 3: Data summarization"""

dfpayment_enriched.groupby('source_id').agg(count_product_id=("product_id","count"),count_category=("category","count"),sum_volume=("volume","sum"))

dfpayment_enriched.groupby('team_own').agg(count_product_id=("product_id","count"),count_category=("category","count"),sum_volume=("volume","sum"))

dfpayment_enriched.groupby('category').agg(count_product_id=("product_id","count"),count_category=("category","count"),sum_volume=("volume","sum"))

"""2. **Table**: dftransactions"""

#1/ xem dữ liệu mẫu .head()
dftransactions.head()

#2/ kiểm tra kiểu dữ liệu, missing .info()
dftransactions.info()

"""- Missing:** sender_id, receiver_id, extra_info**
=> Check dữ liệu thiếu cột sender_id, receiver_id
- Datatype: Check timeStamp, đổi về datetime
"""

# Missing value in sender_id column
print(dftransactions['sender_id'].isna().sum())

# Missing value in sender_id column
nan_rows = dftransactions[dftransactions['sender_id'].isna()]
nan_rows.head()

# Missing value in receiver_id column
print(dftransactions['receiver_id'].isna().sum())

# Missing value in receiver_id column
nan_rows = dftransactions[dftransactions['receiver_id'].isna()]
nan_rows.head()

#3/thống kê dữ liệu số .describe()
dftransactions.describe()

"""- Incorrect: cột reveiver_id có giá trị âm
- volume column: Potential outlier
- volume column: Distribution appears right-skewed (mean > median)
- volume column: High variability based on std
-  volume column: data spread out
"""

#4/phân bố categorical .value_counts()
dftransactions['transType'].value_counts()

dftransactions['transStatus'].value_counts()

dftransactions['sender_id'].value_counts()

dftransactions['receiver_id'].value_counts()

#5/Histogram: xem phân phối dữ liệu #sns.histplot(data=DATAFRAME, x="COLUMN")
import seaborn as sns
import matplotlib.pyplot as plt
fig, ax=plt.subplots(figsize=(6,3))
sns.histplot(data=dftransactions, x="volume",bins=50)
plt.show()

sns.boxplot(x=dftransactions["volume"])
plt.show()

import seaborn as sns
import numpy as np
sns.histplot(
    np.log1p(dftransactions["volume"]),
    bins=30
)
plt.show()

"""Step 2: Data validation"""

#1/ chỉ xem kiểu dữ liệu .dtypes
dftransactions.dtypes

#Chỉnh kiểu dữ liệu
dftransactions['timeStamp']=pd.to_datetime(dftransactions['timeStamp'])
dftransactions.head()

sns.boxplot(x="volume",y="transType",data=dftransactions)
plt.show()

#Check duplicated
dftransactions.duplicated().sum()

"""Result: Need to remove dupplicated

Step 3: Data summarization
"""

dftransactions.groupby('transType').agg(count_transaction_id=("transaction_id","count"),count_merchant_id=("merchant_id","count"),sum_volume=("volume","sum"))

dftransactions.groupby('transStatus').agg(count_transaction_id=("transaction_id","count"),count_merchant_id=("merchant_id","count"),sum_volume=("volume","sum"))

"""**Part II: Data Wrangling**

1. Table:  **dfpayment_enriched**

Q1: Top 3 product_ids with the highest volume.
"""

dfpayment_enriched.head(6)

dfpayment_enriched.groupby('product_id').agg(sum_volume=('volume','sum')).sort_values(by='sum_volume', ascending=False).head(3)

"""Q2.Given that 1 product_id is only owed by 1 team, are there any abnormal products against this rule?

"""

#Groupby by product_id, count unique team_own
dfQ2=dfpayment_enriched.groupby('product_id')['team_own'].nunique()
#No abnormal products
dfQ2[dfQ2 > 1]

#Check again
dfpayment_enriched.groupby('product_id')['team_own'].nunique().sort_values(ascending=False).head(5)

dfQ2[dfQ2 == 0] # Check ==0

dfpayment_enriched[dfpayment_enriched['product_id'].isin([3, 1976, 10033])]

"""Q3.Find the team has had the lowest performance (lowest volume) since Q2.2023. Find the category that contributes the least to that team."""

dfpayment_enriched_Q2=dfpayment_enriched[dfpayment_enriched['report_month']=="2023-02"]
lowest_team_Q2=dfpayment_enriched_Q2.groupby('team_own').agg(lowest_performance=('volume','sum')).sort_values(by='lowest_performance',ascending=True).head(1)
lowest_team_Q2

dfpayment_enriched_Q2_APS=dfpayment_enriched_Q2[dfpayment_enriched_Q2['team_own']==lowest_team_Q2.index[0]]
dfpayment_enriched_Q2_APS.groupby('product_id').agg(lowest_performance=('volume','sum')).sort_values(by='lowest_performance',ascending=True).head(1)

"""Q4. Find the contribution of source_ids of refund transactions (payment_group = ‘refund’), what is the source_id with the highest contribution?

"""

dfpayment_enriched_refund=dfpayment_enriched[dfpayment_enriched['payment_group']=="refund"]
highest_source=dfpayment_enriched_refund.groupby('source_id').agg(highest_performance=('volume','sum')).sort_values(by='highest_performance',ascending=False).head(1)
highest_source

"""2. Table **transactions.csv**

Q5. Define type of transactions (‘transaction_type’) for each row, given:
- transType = 2 & merchant_id = 1205: Bank Transfer Transaction
- transType = 2 & merchant_id = 2260: Withdraw Money Transaction
- transType = 2 & merchant_id = 2270: Top Up Money Transaction
- transType = 2 & others merchant_id: Payment Transaction
- transType = 8, merchant_id = 2250: Transfer Money Transaction
- transType = 8 & others merchant_id: Split Bill Transaction
- Remained cases are invalid transactions
"""

import numpy as np

conditions = [
    (dftransactions['transType'] == 2) & (dftransactions['merchant_id'] == 1205),
    (dftransactions['transType'] == 2) & (dftransactions['merchant_id'] == 2260),
    (dftransactions['transType'] == 2) & (dftransactions['merchant_id'] == 2270),
    (dftransactions['transType'] == 2),
    (dftransactions['transType'] == 8) & (dftransactions['merchant_id'] == 2250),
    (dftransactions['transType'] == 8)
]

choices = [
    'Bank Transfer Transaction',
    'Withdraw Money Transaction',
    'Top Up Money Transaction',
    'Payment Transaction',
    'Transfer Money Transaction',
    'Split Bill Transaction'
]

dftransactions['transaction_type'] = np.select(conditions, choices, default='Invalid Transaction')

dftransactions.head()

"""Q6.Of each transaction type (excluding invalid transactions): find the number of transactions, volume, senders and receivers."""

dftransactions_Q6=dftransactions[dftransactions['transaction_type']!="Invalid Transaction"]
dftransactions_Q6.groupby('transaction_type').agg(count_transactions=('transaction_id','count'),sum_volume=('volume','sum'),count_senders=('sender_id','nunique'),count_receivers=('receiver_id','nunique'))